### ISSUE TITLE
load wiktionary links in wiktionary-bro.

### ISSUE THREAD

**Issue by mooseyboots** [agzam/wiktionary-bro.el#11]
it shouldn't be too hard to save a text prop as the term of a wiktionary link, then have a command on RET to call wiktionary-bro using that term. i've done it in other emacs dictionary interfaces.

it might also be worth having TAB move forward from link to link, to allow for easy nav to and load links. something like `C-c i` could be used for folding, as its already familiar from org.

**Comment by agzam** [comment]
As I mentioned somewhere else, I'm currently messing around (whenever I get a chance) with having the Wiktionary buffer in Org-Mode, where the links, should work as normal, Org-Mode links. That's the plan, anyway.
